### ISSUE TITLE
Nice Project

### ISSUE THREAD

**Issue by Kokrra** [BCGDV-ASIA/android-widget-connectpattern#2]
How to make to save the pattern and open a page with it?

**Comment by alphamu** [comment]
The sample app shows how you can listen for what pattern has been drawn. Effectively, you are returned a list of integers that represent the pattern. If the list of integers (i.e. the pattern) is what you expect, you can take any action in the listener.

```
view.setOnConnectPatternListener(new ConnectPatternView.OnConnectPatternListener() {
        @Override
        public void onPatternEntered(ArrayList<Integer> result) {
            //check result
        }
       ...
```

If you want to create the pattern in your code, that's not currently possible. Feel free to raise a feature request, but that's not really the purpose of the widget.
