### ISSUE TITLE
Proximity thresholds - too sensitive.

### ISSUE THREAD

**Issue by RunYouCleverBoy** [BCGDV-ASIA/android-widget-connectpattern#3]
Hi.
Great engine. Correctly engineered. Just one thing: Can you please make the thresholds of the proximity to dots more conservative? 
It is a bit frustrating to draw a diagonal around a point.

Thanks.

**Comment by alphamu** [comment]
I'm not sure I understand your requirement. In the current release you cant really skip a position. If you want to draw a line from 0 - 2, the dot at position 1 will also be included in this line. This is unfortunately by design and I realise this is not the same behaviour as the one observed in the lock pattern.

**Comment by RunYouCleverBoy** [comment]
Hi. Thanks for the reply.
I meant... Diagonal between 2 *adjacent* points.

For the explanation of the issue, let's call them by numbers:
1 2 3
4 5 6
7 8 9

Now, try to draw a line from 4 to 2.

It seems very hard to do. It has to be very accurate.
Point 1 and 5 always "hijack" it on the way.

In my most humble opinion, when first touching, the sensitive radius around the 1st point should be large, when dragging, it should be small.

The human brain is pretty good (more or less) when dragging, but it misses when hitting a point with the finger.


Thanks

**Comment by alphamu** [comment]
How big is the widget in this scenario? I'll investigate.

**Comment by RunYouCleverBoy** [comment]
Almost full screen. Full with ~1cm padding.
I use Nexus 5. Full screen gives same results.
Simplest example is the code 7, 4, 2, 3 (easiest to draw with the right thumb). 
Sometimes it takes a while before I hit the first point, then, most of the times it goes
7, 4, 5, 2, 3 ("stairway" pattern).


```
* *-*
 /
* * *
| 
* * *

```
Turns
```
* *-*
  |
*-* *
|
* * *

```
Thanks

**Comment by alphamu** [comment]
I'll investigate, thanks for reporting.

**Comment by alphamu** [comment]
Can you check version `0.2.1`? I've changed the code to not snap unless the line is more or less touching the marker. This should hopefully fix your issue.

**Comment by RunYouCleverBoy** [comment]
Vive la différence! Much better! Practically, the issue is closed, I think. I'd say it's good enough for every practical purpose.

Thanks.

**Comment by alphamu** [comment]
Thanks @RunYouCleverBoy.
If you can, do let us know which app you used our widget in. We'd love to see the results.

**Comment by RunYouCleverBoy** [comment]
Hi. Well, first, I tested it on a playground app. I can send you the sources but it's just a fragment with the lock view.

It simulates the real thing (the greater app), which, I am afraid, needs some authentication further than the pattern. The pattern lock is just for some screen within the protected app.
